name: Deploy to Ubuntu

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/landlinkai/project
            git pull origin main
            # ถ้าเป็น Go
            go build -o main .
            # ถ้าใช้ pm2 หรือ systemd ก็ restart ตรงนี้
            sudo systemctl restart my-app.service